name: simple_rsa2
description: Flutter plugin to encrypt and decrypt string with a public and a private key
version: 2.0.0

homepage: https://github.com/DevelSystems/simple_rsa2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.develsystems.simple_rsa2
        pluginClass: SimpleRsa2Plugin
      ios:
        pluginClass: SimpleRsa2Plugin
